COLLECTION_NAMES = ["Benign_CNV", "Regulatory", "GnomAD", "HI_gene", "HI_region", "Genes"]
CHECK_TYPE_NAMES = ["Benign_CNV"]

LOSS_ATTRIBUTES = GAIN_ATTRIBUTES = [
    "gencode_genes",
    "protein_coding",
    "pseudogenes",
    "mirna",
    "lncrna",
    "rrna",
    "snrna",
    "morbid_genes",
    "disease_associated_genes",
    "hi_genes",
    "regions_HI",
    "regions_TS",
    "regulatory",
    "regulatory_enhancer",
    "regulatory_silencer",
    "regulatory_transcriptional_cis_regulatory_region",
    "regulatory_promoter",
    "regulatory_DNase_I_hypersensitive_site",
    "regulatory_enhancer_blocking_element",
    "regulatory_TATA_box",
]

ALLOWED_CHROMOSOMES = [
    "chr1",
    "chr2",
    "chr3",
    "chr4",
    "chr5",
    "chr6",
    "chr7",
    "chr8",
    "chr9",
    "chr10",
    "chr11",
    "chr12",
    "chr13",
    "chr14",
    "chr15",
    "chr16",
    "chr17",
    "chr18",
    "chr19",
    "chr20",
    "chr21",
    "chr22",
    "chrX",
    "chrY",
]
# LOSS_ATTRIBUTES = [
#     'gencode_genes',
#     'protein_coding',
#     'pseudogenes',
#     'mirna',
#     'lncrna',
#     'rrna',
#     'snrna',
#     'morbid_genes',
#     'disease_associated_genes',
#     'hi_genes',
#     'regions_HI',
#     'regulatory',
#     'regulatory_enhancer',
#     'regulatory_open_chromatin_region',
#     'regulatory_promoter',
#     'regulatory_flanking_region',
#     'regulatory_CTCF_binding_site',
#     'regulatory_TF_binding_site',
#     'regulatory_curated'
# ]


# GAIN_ATTRIBUTES = [
#     'gencode_genes',
#     'protein_coding',
#     'pseudogenes',
#     'mirna',
#     'lncrna',
#     'rrna',
#     'snrna',
#     'morbid_genes',
#     'disease_associated_genes',
#     'regions_TS',
#     'regulatory',
#     'regulatory_enhancer',
#     'regulatory_open_chromatin_region',
#     'regulatory_promoter',
#     'regulatory_flanking_region',
#     'regulatory_CTCF_binding_site',
#     'regulatory_TF_binding_site',
#     'regulatory_curated'
# ]
